<font size=5>Imports</font>

In [5]:
import pandas as pd
import numpy as np

<font size=5>Reading Data</font>

In [6]:
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

<font size=5>Data Preprocessing</font>

In [8]:
df = df.replace('?', np.NaN)
df = df.dropna()
df = df[df["release_year"]>0]
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

<font size=5>Creating Subsets</font>

In [10]:
subsets = df["type"].unique()
subsets

array(['Movie', 'TV Show'], dtype=object)

In [13]:
Movies = df[df["type"] == "Movie"]
Series = df[df["type"] == "TV Show"]

In [14]:
Movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...

In [16]:
Series.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
198,s199,TV Show,King of Boys: The Return of the King,Kemi Adetiba,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,"August 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...
273,s274,TV Show,Gone for Good,Juan Carlos Medina,"Finnegan Oldfield, Nicolas Duvauchelle, Guilla...",France,"August 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","Ten years after losing two loved ones, a man i..."
276,s277,TV Show,Valeria,Inma Torrente,"Diana Gómez, Silma López, Paula Malia, Teresa ...",Spain,"August 13, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, Spa...",A writer in creative and marital crises finds ...
297,s298,TV Show,Navarasa,"Bejoy Nambiar, Priyadarshan, Karthik Narain, V...","Suriya, Vijay Sethupathi, Revathy, Prakash Raj...",India,"August 6, 2021",2021,TV-MA,1 Season,TV Shows,"From amusement to awe, the nine human emotions..."

<font size=5>Merging Subsets</font>

In [20]:
df_merged = pd.concat([Movies,Series], keys=["Movies", "Series"])
df_merged

            show_id     type  \
Movies 7         s8    Movie
       9        s10    Movie
       12       s13    Movie
       24       s25    Movie
       27       s28    Movie
...             ...      ...
Series 8172   s8173  TV Show
       8214   s8215  TV Show
       8293   s8294  TV Show
       8302   s8303  TV Show
       8599   s8600  TV Show

                                                        title  \
Movies 7                                              Sankofa
       9                                         The Starling
       12                                        Je Suis Karl
       24                                               Jeans
       27                                           Grown Ups
...                                                       ...
Series 8172             Th Eena Meena Deeka Chase Comedy Show
       8214  The Blue Planet: A Natural History of the Oceans
       8293                                          The Fear
       8302                                          The Five
       8599                                   Toast of London

                        director  \
Movies 7            Haile Gerima
       9          Theodore Melfi
       12    Christian Schwochow
       24             S. Shankar
       27           Dennis Dugan
...                          ...
Series 8172        Dheeraj Berry
       8214  Alastair Fothergill
       8293      Michael Samuels
       8302        Mark Tonderai
       8599      Michael Cumming

                                                          cast  \
Movies 7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
       9     Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
       12    Luna Wedler, Jannis Niewöhner, Milan Peschel, ...
       24    Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...
       27    Adam Sandler, Kevin James, Chris Rock, David S...
...                                                        ...
Series 8172                           Sanjay Keni, Priya Raina
       8214                                 David Attenborough
       8293  Peter Mullan, Anastasia Hille, Harry Lloyd, Pa...
       8302  Tom Cullen, O.T. Fagbenle, Lee Ingleby, Sarah ...
       8599  Matt Berry, Robert Bathurst, Doon Mackichan, S...

                                                       country  \
Movies 7     United States, Ghana, Burkina Faso, United Kin...
       9                                         United States
       12                              Germany, Czech Republic
       24                                                India
       27                                        United States
...                                                        ...
Series 8172                                              India
       8214                                     United Kingdom
       8293                                     United Kingdom
       8302                                     United Kingdom
       8599                                     United Kingdom

                     date_added  release_year rating   duration  \
Movies 7     September 24, 2021          1993  TV-MA    125 min
       9     September 24, 2021          2021  PG-13    104 min
       12    September 23, 2021          2021  TV-MA    127 min
       24    September 21, 2021          1998  TV-14    166 min
       27    September 20, 2021          2010  PG-13    103 min
...                         ...           ...    ...        ...
Series 8172      March 31, 2018          2015  TV-Y7   1 Season
       8214    October 10, 2015          2001   TV-G   1 Season
       8293      March 31, 2017          2012  TV-MA   1 Season
       8302  September 15, 2017          2016  TV-MA   1 Season
       8599   September 1, 2017          2015  TV-MA  3 Seasons

                                                     listed_in  \
Movies 7      Dramas, Independent Movies, International Movies
       9                                      Comedies, Dramas
       12                         Dramas, International Movies
       24      Comedies, International Movies, Romantic Movies
       27                                             Comedies
...                                                        ...
Series 8172                              Kids' TV, TV Comedies
       8214  British TV Shows, Docuseries, International TV...
       8293        British TV Shows, Crime TV Shows, TV Dramas
       8302        British TV Shows, Crime TV Shows, TV Dramas
       8599   British TV Shows, Classic & Cult TV, TV Comedies

                                                   description
Movies 7     On a photo shoot in Ghana, an American model s...
       9     A woman adjusting to life after a loss contend...
       12    After most of her family is murdered in a terr...
       24    When the father of the man she loves insists t...
       27    Mourning the loss of their beloved junior high...
...                                                        ...
Series 8172  A hungry fox and three resourceful, surprising...
       8214  David Attenborough narrates this definitive ex...
       8293  Richie Beckett is an aging Brighton crime boss...
       8302  Twenty years after 5-year-old Jesse disappears...
       8599  After a divorce and fatal career move, a class...

[5332 rows x 12 columns]

<font size=5>Sorting Data</font>

In [23]:
df = df.sort_values("release_year")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8640,s8641,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...
7219,s7220,Movie,Know Your Enemy - Japan,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"March 31, 2017",1945,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...
7294,s7295,Movie,Let There Be Light,John Huston,Walter Huston,United States,"March 31, 2017",1946,TV-PG,58 min,"Classic Movies, Documentaries",Some returning combat veterans suffer scars th...
8587,s8588,Movie,Thunderbolt,"William Wyler, John Sturges","James Stewart, Lloyd Bridges",United States,"March 31, 2017",1947,TV-PG,42 min,"Classic Movies, Documentaries",A P-47 Thunderbolt squadron is shown in prepar...

<font size=5>Transposing Data</font>

In [24]:
df_transpose = df.transpose()
df_transpose.head()

,8205,8640,7219,7294,8587,1699,2375,8506,7954,7839,...,1281,1318,284,983,1223,910,966,279,1341,1304
show_id,s8206,s8641,s7220,s7295,s8588,s1700,s2376,s8507,s7955,s7840,...,s1282,s1319,s285,s984,s1224,s911,s967,s280,s1342,s1305
type,Movie,Movie,Movie,Movie,Movie,Movie,Movie,Movie,Movie,Movie,...,Movie,Movie,Movie,Movie,TV Show,Movie,Movie,Movie,Movie,Movie
title,The Battle of Midway,Tunisian Victory,Know Your Enemy - Japan,Let There Be Light,Thunderbolt,White Christmas,The Blazing Sun,The Sign of Venus,Scandal in Sorrento,Rebel Without a Cause,...,Red,To All The Boys: Always And Forever,The Kissing Booth 3,Heroes: Silence and Rock & Roll,Dealer,Monster,Get the Grift,Monster Hunter: Legends of the Guild,Malcolm & Marie,Animals on the Loose: A You vs. Wild Movie
director,John Ford,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...","Frank Capra, Joris Ivens",John Huston,"William Wyler, John Sturges",Michael Curtiz,Youssef Chahine,Dino Risi,Dino Risi,Nicholas Ray,...,Tirumala Kishore,Michael Fimognari,Vince Marcello,Alexis Morante,"Ange Basterga, Nicolas Lopez",Anthony Mandler,Pedro Antonio,Steven Yamamoto,Sam Levinson,Ben Simms
cast,"Henry Fonda, Jane Darwell",Burgess Meredith,"Walter Huston, Dana Andrews",Walter Huston,"James Stewart, Lloyd Bridges","Bing Crosby, Danny Kaye, Rosemary Clooney, Ver...","Omar Sharif, Faten Hamama, Zaki Rostom, Farid ...","Sophia Loren, Franca Valeri, Vittorio De Sica,...","Vittorio De Sica, Sophia Loren, Lea Padovani, ...","James Dean, Natalie Wood, Sal Mineo, Jim Backu...",...,"Ram Pothineni, Nivetha Pethuraj, Malvika Sharm...","Lana Condor, Noah Centineo, Janel Parrish, Ann...","Joey King, Joel Courtney, Jacob Elordi, Molly ...","Enrique Bunbury, Juan Valdivia, Joaquín Cardie...","Abdramane Diakité, Mohamed Boudouh, Sébastien ...","Kelvin Harrison Jr., Jennifer Hudson, Jeffrey ...","Marcus Majella, Samantha Schmütz, Caito Mainie...","Ben Rausch, Erica Lindbeck, Dante Basco, Brand...","Zendaya, John David Washington",Bear Grylls

<font size=5>Melting Data</font>

In [25]:
df_melted = df.melt()
df_melted.head()

  variable  value
0  show_id  s8206
1  show_id  s8641
2  show_id  s7220
3  show_id  s7295
4  show_id  s8588

<font size=5>Casting Data</font>

In [28]:
df["release_year"] = df["release_year"].astype(float)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942.0,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8640,s8641,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944.0,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...
7219,s7220,Movie,Know Your Enemy - Japan,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"March 31, 2017",1945.0,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...
7294,s7295,Movie,Let There Be Light,John Huston,Walter Huston,United States,"March 31, 2017",1946.0,TV-PG,58 min,"Classic Movies, Documentaries",Some returning combat veterans suffer scars th...
8587,s8588,Movie,Thunderbolt,"William Wyler, John Sturges","James Stewart, Lloyd Bridges",United States,"March 31, 2017",1947.0,TV-PG,42 min,"Classic Movies, Documentaries",A P-47 Thunderbolt squadron is shown in prepar...